/*
 * Copyright 2021 The Knative Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	internalskafkaeventingv1alpha1 "knative.dev/eventing-kafka-broker/control-plane/pkg/apis/internalskafkaeventing/v1alpha1"
	scheme "knative.dev/eventing-kafka-broker/control-plane/pkg/client/clientset/versioned/scheme"
)

// ConsumersGetter has a method to return a ConsumerInterface.
// A group's client should implement this interface.
type ConsumersGetter interface {
	Consumers(namespace string) ConsumerInterface
}

// ConsumerInterface has methods to work with Consumer resources.
type ConsumerInterface interface {
	Create(ctx context.Context, consumer *internalskafkaeventingv1alpha1.Consumer, opts v1.CreateOptions) (*internalskafkaeventingv1alpha1.Consumer, error)
	Update(ctx context.Context, consumer *internalskafkaeventingv1alpha1.Consumer, opts v1.UpdateOptions) (*internalskafkaeventingv1alpha1.Consumer, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, consumer *internalskafkaeventingv1alpha1.Consumer, opts v1.UpdateOptions) (*internalskafkaeventingv1alpha1.Consumer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*internalskafkaeventingv1alpha1.Consumer, error)
	List(ctx context.Context, opts v1.ListOptions) (*internalskafkaeventingv1alpha1.ConsumerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *internalskafkaeventingv1alpha1.Consumer, err error)
	ConsumerExpansion
}

// consumers implements ConsumerInterface
type consumers struct {
	*gentype.ClientWithList[*internalskafkaeventingv1alpha1.Consumer, *internalskafkaeventingv1alpha1.ConsumerList]
}

// newConsumers returns a Consumers
func newConsumers(c *InternalV1alpha1Client, namespace string) *consumers {
	return &consumers{
		gentype.NewClientWithList[*internalskafkaeventingv1alpha1.Consumer, *internalskafkaeventingv1alpha1.ConsumerList](
			"consumers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *internalskafkaeventingv1alpha1.Consumer { return &internalskafkaeventingv1alpha1.Consumer{} },
			func() *internalskafkaeventingv1alpha1.ConsumerList {
				return &internalskafkaeventingv1alpha1.ConsumerList{}
			},
		),
	}
}
