ignore:
  - "**/zz_generated*.go" # Ignore generated files.
  - "pkg/client"
  - "third_party"
  - "vendor"
  - "data-plane/contract"
  - "hack"
  - "test"
  - "control-plane/pkg/reconciler/kafka/testing"
  - "control-plane/pkg/reconciler/testing"
