run:
  timeout: 5m

  build-tags:
    - e2e

linters:
  enable:
    - asciicheck
    - gosec
    - prealloc
    - unconvert
    - unparam
  disable:
    - errcheck

issues:
  exclude-dirs:
    - control-plane/pkg/client
    - data-plane
  exclude-rules:
    - path: test # Excludes /test, *_test.go etc.
      linters:
        - gosec
        - unparam
