version: "2"
run:
  build-tags:
    - e2e
linters:
  enable:
    - asciicheck
    - gosec
    - prealloc
    - unconvert
    - unparam
  disable:
    - errcheck
  settings:
    gosec:
      excludes:
        - G101
        - G115
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - prealloc
        path: _test\.go
      - linters:
          - prealloc
          - gosec
          - unparam
        path: test
      - linters:
          - staticcheck
        text: CreateACL is deprecated
      - linters:
          - unparam
        path: control-plane/pkg/security/oauth/msk_access_token_issuer.go
    paths:
      - control-plane/pkg/client
      - data-plane
      - third_party
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
