version: "2"
run:
  build-tags:
    - e2e
linters:
  enable:
    - asciicheck
    - gosec
    - prealloc
    - unconvert
    - unparam
  disable:
    - errcheck
  settings:
    gosec:
      excludes:
        - G115
    staticcheck:
      checks:
        - all
        - "-ST1019"
        - "-ST1003"
        - "-ST1012"
        - "-ST1016"
        - "-ST1001"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
          - unparam
        path: test
    paths:
      - control-plane/pkg/client
      - data-plane
      - third_party
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
