apiVersion: v1
kind: Service
metadata:
  name: event-display-2
spec:
  selector:
    app: event-display-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: label-demo-2
  labels:
    app: event-display-2
spec:
  containers:
  - name: event-display-2
    image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: event-display
spec:
  selector:
    app: event-display
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
    app: event-display
spec:
  containers:
  - name: event-display
    image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
    ports:
    - containerPort: 8080
---
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumers: 15
  consumerGroup: knative-group
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092 # note the kafka namespace
  topics:
  - knative-demo-topic
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display