/*
 * Copyright 2021 The Knative Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	eventingv1alpha1 "knative.dev/eventing-kafka-broker/control-plane/pkg/apis/eventing/v1alpha1"
)

// KafkaSinkLister helps list KafkaSinks.
// All objects returned here must be treated as read-only.
type KafkaSinkLister interface {
	// List lists all KafkaSinks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*eventingv1alpha1.KafkaSink, err error)
	// KafkaSinks returns an object that can list and get KafkaSinks.
	KafkaSinks(namespace string) KafkaSinkNamespaceLister
	KafkaSinkListerExpansion
}

// kafkaSinkLister implements the KafkaSinkLister interface.
type kafkaSinkLister struct {
	listers.ResourceIndexer[*eventingv1alpha1.KafkaSink]
}

// NewKafkaSinkLister returns a new KafkaSinkLister.
func NewKafkaSinkLister(indexer cache.Indexer) KafkaSinkLister {
	return &kafkaSinkLister{listers.New[*eventingv1alpha1.KafkaSink](indexer, eventingv1alpha1.Resource("kafkasink"))}
}

// KafkaSinks returns an object that can list and get KafkaSinks.
func (s *kafkaSinkLister) KafkaSinks(namespace string) KafkaSinkNamespaceLister {
	return kafkaSinkNamespaceLister{listers.NewNamespaced[*eventingv1alpha1.KafkaSink](s.ResourceIndexer, namespace)}
}

// KafkaSinkNamespaceLister helps list and get KafkaSinks.
// All objects returned here must be treated as read-only.
type KafkaSinkNamespaceLister interface {
	// List lists all KafkaSinks in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*eventingv1alpha1.KafkaSink, err error)
	// Get retrieves the KafkaSink from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*eventingv1alpha1.KafkaSink, error)
	KafkaSinkNamespaceListerExpansion
}

// kafkaSinkNamespaceLister implements the KafkaSinkNamespaceLister
// interface.
type kafkaSinkNamespaceLister struct {
	listers.ResourceIndexer[*eventingv1alpha1.KafkaSink]
}
