/*
 * Copyright 2020 The Knative Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "knative.dev/eventing-kafka-broker/control-plane/pkg/apis/eventing/v1alpha1"
)

// KafkaSinkLister helps list KafkaSinks.
type KafkaSinkLister interface {
	// List lists all KafkaSinks in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.KafkaSink, err error)
	// KafkaSinks returns an object that can list and get KafkaSinks.
	KafkaSinks(namespace string) KafkaSinkNamespaceLister
	KafkaSinkListerExpansion
}

// kafkaSinkLister implements the KafkaSinkLister interface.
type kafkaSinkLister struct {
	indexer cache.Indexer
}

// NewKafkaSinkLister returns a new KafkaSinkLister.
func NewKafkaSinkLister(indexer cache.Indexer) KafkaSinkLister {
	return &kafkaSinkLister{indexer: indexer}
}

// List lists all KafkaSinks in the indexer.
func (s *kafkaSinkLister) List(selector labels.Selector) (ret []*v1alpha1.KafkaSink, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.KafkaSink))
	})
	return ret, err
}

// KafkaSinks returns an object that can list and get KafkaSinks.
func (s *kafkaSinkLister) KafkaSinks(namespace string) KafkaSinkNamespaceLister {
	return kafkaSinkNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// KafkaSinkNamespaceLister helps list and get KafkaSinks.
type KafkaSinkNamespaceLister interface {
	// List lists all KafkaSinks in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.KafkaSink, err error)
	// Get retrieves the KafkaSink from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.KafkaSink, error)
	KafkaSinkNamespaceListerExpansion
}

// kafkaSinkNamespaceLister implements the KafkaSinkNamespaceLister
// interface.
type kafkaSinkNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all KafkaSinks in the indexer for a given namespace.
func (s kafkaSinkNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.KafkaSink, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.KafkaSink))
	})
	return ret, err
}

// Get retrieves the KafkaSink from the indexer for a given namespace and name.
func (s kafkaSinkNamespaceLister) Get(name string) (*v1alpha1.KafkaSink, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("kafkasink"), name)
	}
	return obj.(*v1alpha1.KafkaSink), nil
}
