// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/def/triggers.proto

package config

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Trigger struct {
	// attributes filters events by exact match on event context attributes.
	// Each key in the map is compared with the equivalent key in the event
	// context. An event passes the filter if all values are equal to the
	// specified values.
	//
	// Nested context attributes are not supported as keys. Only string values are supported.
	Attributes map[string]string `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// destination is the address that receives events from the Broker that pass the Filter.
	Destination string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	// trigger identifier
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trigger) Reset()         { *m = Trigger{} }
func (m *Trigger) String() string { return proto.CompactTextString(m) }
func (*Trigger) ProtoMessage()    {}
func (*Trigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cd32e421bcc2dd3, []int{0}
}

func (m *Trigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trigger.Unmarshal(m, b)
}
func (m *Trigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trigger.Marshal(b, m, deterministic)
}
func (m *Trigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trigger.Merge(m, src)
}
func (m *Trigger) XXX_Size() int {
	return xxx_messageInfo_Trigger.Size(m)
}
func (m *Trigger) XXX_DiscardUnknown() {
	xxx_messageInfo_Trigger.DiscardUnknown(m)
}

var xxx_messageInfo_Trigger proto.InternalMessageInfo

func (m *Trigger) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Trigger) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Trigger) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Broker struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// the Kafka topic to consume.
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// dead letter sink URI
	DeadLetterSink string `protobuf:"bytes,3,opt,name=deadLetterSink,proto3" json:"deadLetterSink,omitempty"`
	// triggers associated with the broker
	Triggers             []*Trigger `protobuf:"bytes,4,rep,name=triggers,proto3" json:"triggers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Broker) Reset()         { *m = Broker{} }
func (m *Broker) String() string { return proto.CompactTextString(m) }
func (*Broker) ProtoMessage()    {}
func (*Broker) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cd32e421bcc2dd3, []int{1}
}

func (m *Broker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Broker.Unmarshal(m, b)
}
func (m *Broker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Broker.Marshal(b, m, deterministic)
}
func (m *Broker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Broker.Merge(m, src)
}
func (m *Broker) XXX_Size() int {
	return xxx_messageInfo_Broker.Size(m)
}
func (m *Broker) XXX_DiscardUnknown() {
	xxx_messageInfo_Broker.DiscardUnknown(m)
}

var xxx_messageInfo_Broker proto.InternalMessageInfo

func (m *Broker) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Broker) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Broker) GetDeadLetterSink() string {
	if m != nil {
		return m.DeadLetterSink
	}
	return ""
}

func (m *Broker) GetTriggers() []*Trigger {
	if m != nil {
		return m.Triggers
	}
	return nil
}

type Brokers struct {
	Broker               []*Broker `protobuf:"bytes,1,rep,name=broker,proto3" json:"broker,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Brokers) Reset()         { *m = Brokers{} }
func (m *Brokers) String() string { return proto.CompactTextString(m) }
func (*Brokers) ProtoMessage()    {}
func (*Brokers) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cd32e421bcc2dd3, []int{2}
}

func (m *Brokers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Brokers.Unmarshal(m, b)
}
func (m *Brokers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Brokers.Marshal(b, m, deterministic)
}
func (m *Brokers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Brokers.Merge(m, src)
}
func (m *Brokers) XXX_Size() int {
	return xxx_messageInfo_Brokers.Size(m)
}
func (m *Brokers) XXX_DiscardUnknown() {
	xxx_messageInfo_Brokers.DiscardUnknown(m)
}

var xxx_messageInfo_Brokers proto.InternalMessageInfo

func (m *Brokers) GetBroker() []*Broker {
	if m != nil {
		return m.Broker
	}
	return nil
}

func init() {
	proto.RegisterType((*Trigger)(nil), "Trigger")
	proto.RegisterMapType((map[string]string)(nil), "Trigger.AttributesEntry")
	proto.RegisterType((*Broker)(nil), "Broker")
	proto.RegisterType((*Brokers)(nil), "Brokers")
}

func init() { proto.RegisterFile("proto/def/triggers.proto", fileDescriptor_3cd32e421bcc2dd3) }

var fileDescriptor_3cd32e421bcc2dd3 = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xa6, 0x9d, 0x6e, 0xf3, 0x0d, 0xa7, 0x04, 0x0f, 0x45, 0x10, 0xc7, 0x10, 0x19, 0xc2, 0x52,
	0xd0, 0xcb, 0x10, 0x3c, 0x38, 0xf1, 0xe6, 0xa9, 0x7a, 0x12, 0x3c, 0x64, 0xcd, 0x5b, 0x09, 0x19,
	0x49, 0x49, 0xdf, 0x0a, 0x03, 0xff, 0x2c, 0xff, 0x40, 0x69, 0x9a, 0x8e, 0xb1, 0xdb, 0xfb, 0x7e,
	0xbc, 0x2f, 0xe1, 0x7b, 0x90, 0x94, 0xce, 0x92, 0x4d, 0x25, 0xae, 0x53, 0x72, 0xaa, 0x28, 0xd0,
	0x55, 0xdc, 0x53, 0xd3, 0xbf, 0x08, 0x06, 0x5f, 0x2d, 0xc5, 0x16, 0x00, 0x82, 0xc8, 0xa9, 0xd5,
	0x96, 0xb0, 0x4a, 0xa2, 0x49, 0x6f, 0x36, 0x7a, 0x4c, 0x78, 0x50, 0xf9, 0xeb, 0x5e, 0x7a, 0x37,
	0xe4, 0x76, 0xd9, 0x81, 0x97, 0x4d, 0x60, 0x24, 0xb1, 0x22, 0x65, 0x04, 0x29, 0x6b, 0x92, 0x78,
	0x12, 0xcd, 0xce, 0xb2, 0x43, 0x8a, 0x8d, 0x21, 0x56, 0x32, 0xe9, 0x79, 0x21, 0x56, 0xf2, 0xfa,
	0x05, 0x2e, 0x8e, 0x02, 0xd9, 0x25, 0xf4, 0x34, 0xee, 0x92, 0xc8, 0x7b, 0x9a, 0x91, 0x5d, 0xc1,
	0x69, 0x2d, 0x36, 0x5b, 0x0c, 0x81, 0x2d, 0x78, 0x8e, 0x17, 0xd1, 0xf4, 0x17, 0xfa, 0x4b, 0x67,
	0x35, 0xba, 0x10, 0x1c, 0x75, 0xc1, 0xcd, 0x0e, 0xd9, 0x52, 0xe5, 0xdd, 0x8e, 0x07, 0xec, 0x1e,
	0xc6, 0x12, 0x85, 0xfc, 0x40, 0x22, 0x74, 0x9f, 0xca, 0xe8, 0xf0, 0x95, 0x23, 0x96, 0xdd, 0xc1,
	0xb0, 0x2b, 0x28, 0x39, 0xf1, 0x05, 0x0c, 0xbb, 0x02, 0xb2, 0xbd, 0x32, 0x7d, 0x80, 0x41, 0xfb,
	0x7a, 0xc5, 0x6e, 0xa1, 0xbf, 0xf2, 0x63, 0xe8, 0x6b, 0xc0, 0x5b, 0x25, 0x0b, 0xf4, 0xf2, 0x07,
	0xe6, 0x12, 0x6b, 0xae, 0x9b, 0x1e, 0x6a, 0xe4, 0x58, 0xa3, 0x21, 0x65, 0x0a, 0xae, 0xc5, 0x5a,
	0x0b, 0xde, 0x9a, 0x78, 0x6e, 0x1d, 0xf2, 0xdc, 0x9a, 0xb5, 0x2a, 0x96, 0xe7, 0x21, 0xfa, 0xcd,
	0xc3, 0xef, 0x9b, 0xdc, 0x1a, 0x72, 0x76, 0x33, 0x2f, 0x37, 0xc2, 0x60, 0x5a, 0xea, 0x22, 0x6d,
	0xdc, 0x69, 0xeb, 0x5e, 0xf5, 0xfd, 0x19, 0x9f, 0xfe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x53, 0x20,
	0x2e, 0x7c, 0xe2, 0x01, 0x00, 0x00,
}
