#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

DATA_PLANE_OUTPUT_DIR=./data-plane/generated/src/main/java
CONTROL_PLANE_OUTPUT_DIR=./

mkdir -p $DATA_PLANE_OUTPUT_DIR
mkdir -p $CONTROL_PLANE_OUTPUT_DIR

docker run --rm -u "$(id -g)":"$(id -u)" -v "${PWD}":"${PWD}" -w "${PWD}" jaegertracing/protobuf:latest \
  --proto_path="${PWD}" \
  --java_out=$DATA_PLANE_OUTPUT_DIR \
  --go_out=$CONTROL_PLANE_OUTPUT_DIR \
  "${PWD}"/proto/def/*
