#!/usr/bin/env bash

function rm_if_exists() {
  if [ -f "$1" ]; then
    rm -r "$1"
  fi
}

DATA_PLANE_OUTPUT_DIR=./data-plane/generated/src/main/java

rm_if_exists $DATA_PLANE_OUTPUT_DIR

mkdir -p $DATA_PLANE_OUTPUT_DIR
docker run --rm -u "$(id -g)":"$(id -u)" -v "${PWD}":"${PWD}" -w "${PWD}" jaegertracing/protobuf:latest \
  --proto_path="${PWD}" \
  --java_out=$DATA_PLANE_OUTPUT_DIR \
  "${PWD}"/proto/def/*
