//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * Copyright 2021 The Knative Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (kas *KafkaAuthSpec) DeepCopyInto(out *KafkaAuthSpec) {
	*out = *kas
	if kas.BootstrapServers != nil {
		kas, out := &kas.BootstrapServers, &out.BootstrapServers
		*out = make([]string, len(*kas))
		copy(*out, *kas)
	}
	kas.Net.DeepCopyInto(&out.Net)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaAuthSpec.
func (kas *KafkaAuthSpec) DeepCopy() *KafkaAuthSpec {
	if kas == nil {
		return nil
	}
	out := new(KafkaAuthSpec)
	kas.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (kb *KafkaBinding) DeepCopyInto(out *KafkaBinding) {
	*out = *kb
	out.TypeMeta = kb.TypeMeta
	kb.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	kb.Spec.DeepCopyInto(&out.Spec)
	kb.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaBinding.
func (kb *KafkaBinding) DeepCopy() *KafkaBinding {
	if kb == nil {
		return nil
	}
	out := new(KafkaBinding)
	kb.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (kb *KafkaBinding) DeepCopyObject() runtime.Object {
	if c := kb.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (kbl *KafkaBindingList) DeepCopyInto(out *KafkaBindingList) {
	*out = *kbl
	out.TypeMeta = kbl.TypeMeta
	kbl.ListMeta.DeepCopyInto(&out.ListMeta)
	if kbl.Items != nil {
		in, out := &kbl.Items, &out.Items
		*out = make([]KafkaBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaBindingList.
func (kbl *KafkaBindingList) DeepCopy() *KafkaBindingList {
	if kbl == nil {
		return nil
	}
	out := new(KafkaBindingList)
	kbl.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (kbl *KafkaBindingList) DeepCopyObject() runtime.Object {
	if c := kbl.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (kbs *KafkaBindingSpec) DeepCopyInto(out *KafkaBindingSpec) {
	*out = *kbs
	kbs.BindingSpec.DeepCopyInto(&out.BindingSpec)
	kbs.KafkaAuthSpec.DeepCopyInto(&out.KafkaAuthSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaBindingSpec.
func (kbs *KafkaBindingSpec) DeepCopy() *KafkaBindingSpec {
	if kbs == nil {
		return nil
	}
	out := new(KafkaBindingSpec)
	kbs.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (kbs *KafkaBindingStatus) DeepCopyInto(out *KafkaBindingStatus) {
	*out = *kbs
	kbs.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaBindingStatus.
func (kbs *KafkaBindingStatus) DeepCopy() *KafkaBindingStatus {
	if kbs == nil {
		return nil
	}
	out := new(KafkaBindingStatus)
	kbs.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (kbs *KafkaNetSpec) DeepCopyInto(out *KafkaNetSpec) {
	*out = *kbs
	kbs.SASL.DeepCopyInto(&out.SASL)
	kbs.TLS.DeepCopyInto(&out.TLS)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaNetSpec.
func (kbs *KafkaNetSpec) DeepCopy() *KafkaNetSpec {
	if kbs == nil {
		return nil
	}
	out := new(KafkaNetSpec)
	kbs.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (ksas *KafkaSASLSpec) DeepCopyInto(out *KafkaSASLSpec) {
	*out = *ksas
	ksas.User.DeepCopyInto(&out.User)
	ksas.Password.DeepCopyInto(&out.Password)
	ksas.RoleARN.DeepCopyInto(&out.RoleARN)
	ksas.TokenProvider.DeepCopyInto(&out.TokenProvider)
	ksas.Type.DeepCopyInto(&out.Type)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSASLSpec.
func (ksas *KafkaSASLSpec) DeepCopy() *KafkaSASLSpec {
	if ksas == nil {
		return nil
	}
	out := new(KafkaSASLSpec)
	ksas.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (kts *KafkaTLSSpec) DeepCopyInto(out *KafkaTLSSpec) {
	*out = *kts
	kts.Cert.DeepCopyInto(&out.Cert)
	kts.Key.DeepCopyInto(&out.Key)
	kts.CACert.DeepCopyInto(&out.CACert)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaTLSSpec.
func (kts *KafkaTLSSpec) DeepCopy() *KafkaTLSSpec {
	if kts == nil {
		return nil
	}
	out := new(KafkaTLSSpec)
	kts.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (svfs *SecretValueFromSource) DeepCopyInto(out *SecretValueFromSource) {
	*out = *svfs
	if svfs.SecretKeyRef != nil {
		in, out := &svfs.SecretKeyRef, &out.SecretKeyRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretValueFromSource.
func (svfs *SecretValueFromSource) DeepCopy() *SecretValueFromSource {
	if svfs == nil {
		return nil
	}
	out := new(SecretValueFromSource)
	svfs.DeepCopyInto(out)
	return out
}
