/*
 * Copyright 2021 The Knative Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "knative.dev/eventing-kafka-broker/control-plane/pkg/apis/eventing/v1alpha1"
)

// FakeKafkaSinks implements KafkaSinkInterface
type FakeKafkaSinks struct {
	Fake *FakeEventingV1alpha1
	ns   string
}

var kafkasinksResource = schema.GroupVersionResource{Group: "eventing.knative.dev", Version: "v1alpha1", Resource: "kafkasinks"}

var kafkasinksKind = schema.GroupVersionKind{Group: "eventing.knative.dev", Version: "v1alpha1", Kind: "KafkaSink"}

// Get takes name of the kafkaSink, and returns the corresponding kafkaSink object, and an error if there is any.
func (c *FakeKafkaSinks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KafkaSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kafkasinksResource, c.ns, name), &v1alpha1.KafkaSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KafkaSink), err
}

// List takes label and field selectors, and returns the list of KafkaSinks that match those selectors.
func (c *FakeKafkaSinks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KafkaSinkList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kafkasinksResource, kafkasinksKind, c.ns, opts), &v1alpha1.KafkaSinkList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KafkaSinkList{ListMeta: obj.(*v1alpha1.KafkaSinkList).ListMeta}
	for _, item := range obj.(*v1alpha1.KafkaSinkList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kafkaSinks.
func (c *FakeKafkaSinks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kafkasinksResource, c.ns, opts))

}

// Create takes the representation of a kafkaSink and creates it.  Returns the server's representation of the kafkaSink, and an error, if there is any.
func (c *FakeKafkaSinks) Create(ctx context.Context, kafkaSink *v1alpha1.KafkaSink, opts v1.CreateOptions) (result *v1alpha1.KafkaSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kafkasinksResource, c.ns, kafkaSink), &v1alpha1.KafkaSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KafkaSink), err
}

// Update takes the representation of a kafkaSink and updates it. Returns the server's representation of the kafkaSink, and an error, if there is any.
func (c *FakeKafkaSinks) Update(ctx context.Context, kafkaSink *v1alpha1.KafkaSink, opts v1.UpdateOptions) (result *v1alpha1.KafkaSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kafkasinksResource, c.ns, kafkaSink), &v1alpha1.KafkaSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KafkaSink), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKafkaSinks) UpdateStatus(ctx context.Context, kafkaSink *v1alpha1.KafkaSink, opts v1.UpdateOptions) (*v1alpha1.KafkaSink, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kafkasinksResource, "status", c.ns, kafkaSink), &v1alpha1.KafkaSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KafkaSink), err
}

// Delete takes name of the kafkaSink and deletes it. Returns an error if one occurs.
func (c *FakeKafkaSinks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(kafkasinksResource, c.ns, name, opts), &v1alpha1.KafkaSink{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKafkaSinks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kafkasinksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KafkaSinkList{})
	return err
}

// Patch applies the patch and returns the patched kafkaSink.
func (c *FakeKafkaSinks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KafkaSink, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kafkasinksResource, c.ns, name, pt, data, subresources...), &v1alpha1.KafkaSink{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KafkaSink), err
}
