/*
 * Copyright 2021 The Knative Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	eventingv1 "knative.dev/eventing-kafka-broker/control-plane/pkg/apis/eventing/v1"
	scheme "knative.dev/eventing-kafka-broker/control-plane/pkg/client/clientset/versioned/scheme"
)

// KafkaSinksGetter has a method to return a KafkaSinkInterface.
// A group's client should implement this interface.
type KafkaSinksGetter interface {
	KafkaSinks(namespace string) KafkaSinkInterface
}

// KafkaSinkInterface has methods to work with KafkaSink resources.
type KafkaSinkInterface interface {
	Create(ctx context.Context, kafkaSink *eventingv1.KafkaSink, opts metav1.CreateOptions) (*eventingv1.KafkaSink, error)
	Update(ctx context.Context, kafkaSink *eventingv1.KafkaSink, opts metav1.UpdateOptions) (*eventingv1.KafkaSink, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, kafkaSink *eventingv1.KafkaSink, opts metav1.UpdateOptions) (*eventingv1.KafkaSink, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*eventingv1.KafkaSink, error)
	List(ctx context.Context, opts metav1.ListOptions) (*eventingv1.KafkaSinkList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *eventingv1.KafkaSink, err error)
	KafkaSinkExpansion
}

// kafkaSinks implements KafkaSinkInterface
type kafkaSinks struct {
	*gentype.ClientWithList[*eventingv1.KafkaSink, *eventingv1.KafkaSinkList]
}

// newKafkaSinks returns a KafkaSinks
func newKafkaSinks(c *EventingV1Client, namespace string) *kafkaSinks {
	return &kafkaSinks{
		gentype.NewClientWithList[*eventingv1.KafkaSink, *eventingv1.KafkaSinkList](
			"kafkasinks",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *eventingv1.KafkaSink { return &eventingv1.KafkaSink{} },
			func() *eventingv1.KafkaSinkList { return &eventingv1.KafkaSinkList{} },
		),
	}
}
