//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
 * Copyright 2021 The Knative Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	duckv1 "knative.dev/eventing/pkg/apis/duck/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (ks *KafkaSource) DeepCopyInto(out *KafkaSource) {
	*out = *ks
	out.TypeMeta = ks.TypeMeta
	ks.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	ks.Spec.DeepCopyInto(&out.Spec)
	ks.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSource.
func (ks *KafkaSource) DeepCopy() *KafkaSource {
	if ks == nil {
		return nil
	}
	out := new(KafkaSource)
	ks.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (ks *KafkaSource) DeepCopyObject() runtime.Object {
	if c := ks.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (ksl *KafkaSourceList) DeepCopyInto(out *KafkaSourceList) {
	*out = *ksl
	out.TypeMeta = ksl.TypeMeta
	ksl.ListMeta.DeepCopyInto(&out.ListMeta)
	if ksl.Items != nil {
		ksl, out := &ksl.Items, &out.Items
		*out = make([]KafkaSource, len(*ksl))
		for i := range *ksl {
			(*ksl)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSourceList.
func (ksl *KafkaSourceList) DeepCopy() *KafkaSourceList {
	if ksl == nil {
		return nil
	}
	out := new(KafkaSourceList)
	ksl.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (ksl *KafkaSourceList) DeepCopyObject() runtime.Object {
	if c := ksl.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (kss *KafkaSourceSpec) DeepCopyInto(out *KafkaSourceSpec) {
	*out = *kss
	if kss.Consumers != nil {
		kss, out := &kss.Consumers, &out.Consumers
		*out = new(int32)
		**out = **kss
	}
	kss.KafkaAuthSpec.DeepCopyInto(&out.KafkaAuthSpec)
	if kss.Topics != nil {
		kss, out := &kss.Topics, &out.Topics
		*out = make([]string, len(*kss))
		copy(*out, *kss)
	}
	if kss.Delivery != nil {
		kss, out := &kss.Delivery, &out.Delivery
		*out = new(duckv1.DeliverySpec)
		(*kss).DeepCopyInto(*out)
	}
	if kss.Ordering != nil {
		kss, out := &kss.Ordering, &out.Ordering
		*out = new(DeliveryOrdering)
		**out = **kss
	}
	kss.SourceSpec.DeepCopyInto(&out.SourceSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSourceSpec.
func (kss *KafkaSourceSpec) DeepCopy() *KafkaSourceSpec {
	if kss == nil {
		return nil
	}
	out := new(KafkaSourceSpec)
	kss.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (kss *KafkaSourceStatus) DeepCopyInto(out *KafkaSourceStatus) {
	*out = *kss
	kss.SourceStatus.DeepCopyInto(&out.SourceStatus)
	kss.Placeable.DeepCopyInto(&out.Placeable)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KafkaSourceStatus.
func (kss *KafkaSourceStatus) DeepCopy() *KafkaSourceStatus {
	if kss == nil {
		return nil
	}
	out := new(KafkaSourceStatus)
	kss.DeepCopyInto(out)
	return out
}
