/*
 * Copyright 2021 The Knative Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	bindingsv1 "knative.dev/eventing-kafka-broker/control-plane/pkg/apis/bindings/v1"
)

// KafkaBindingLister helps list KafkaBindings.
// All objects returned here must be treated as read-only.
type KafkaBindingLister interface {
	// List lists all KafkaBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*bindingsv1.KafkaBinding, err error)
	// KafkaBindings returns an object that can list and get KafkaBindings.
	KafkaBindings(namespace string) KafkaBindingNamespaceLister
	KafkaBindingListerExpansion
}

// kafkaBindingLister implements the KafkaBindingLister interface.
type kafkaBindingLister struct {
	listers.ResourceIndexer[*bindingsv1.KafkaBinding]
}

// NewKafkaBindingLister returns a new KafkaBindingLister.
func NewKafkaBindingLister(indexer cache.Indexer) KafkaBindingLister {
	return &kafkaBindingLister{listers.New[*bindingsv1.KafkaBinding](indexer, bindingsv1.Resource("kafkabinding"))}
}

// KafkaBindings returns an object that can list and get KafkaBindings.
func (s *kafkaBindingLister) KafkaBindings(namespace string) KafkaBindingNamespaceLister {
	return kafkaBindingNamespaceLister{listers.NewNamespaced[*bindingsv1.KafkaBinding](s.ResourceIndexer, namespace)}
}

// KafkaBindingNamespaceLister helps list and get KafkaBindings.
// All objects returned here must be treated as read-only.
type KafkaBindingNamespaceLister interface {
	// List lists all KafkaBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*bindingsv1.KafkaBinding, err error)
	// Get retrieves the KafkaBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*bindingsv1.KafkaBinding, error)
	KafkaBindingNamespaceListerExpansion
}

// kafkaBindingNamespaceLister implements the KafkaBindingNamespaceLister
// interface.
type kafkaBindingNamespaceLister struct {
	listers.ResourceIndexer[*bindingsv1.KafkaBinding]
}
