/*
 * Copyright 2021 The Knative Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	autoscalingv1 "k8s.io/api/autoscaling/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "knative.dev/eventing-kafka-broker/control-plane/pkg/apis/internals/kafka/eventing/v1alpha1"
	scheme "knative.dev/eventing-kafka-broker/control-plane/pkg/client/internals/kafka/clientset/versioned/scheme"
)

// ConsumerGroupsGetter has a method to return a ConsumerGroupInterface.
// A group's client should implement this interface.
type ConsumerGroupsGetter interface {
	ConsumerGroups(namespace string) ConsumerGroupInterface
}

// ConsumerGroupInterface has methods to work with ConsumerGroup resources.
type ConsumerGroupInterface interface {
	Create(ctx context.Context, consumerGroup *v1alpha1.ConsumerGroup, opts v1.CreateOptions) (*v1alpha1.ConsumerGroup, error)
	Update(ctx context.Context, consumerGroup *v1alpha1.ConsumerGroup, opts v1.UpdateOptions) (*v1alpha1.ConsumerGroup, error)
	UpdateStatus(ctx context.Context, consumerGroup *v1alpha1.ConsumerGroup, opts v1.UpdateOptions) (*v1alpha1.ConsumerGroup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ConsumerGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ConsumerGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ConsumerGroup, err error)
	GetScale(ctx context.Context, consumerGroupName string, options v1.GetOptions) (*autoscalingv1.Scale, error)

	ConsumerGroupExpansion
}

// consumerGroups implements ConsumerGroupInterface
type consumerGroups struct {
	client rest.Interface
	ns     string
}

// newConsumerGroups returns a ConsumerGroups
func newConsumerGroups(c *InternalV1alpha1Client, namespace string) *consumerGroups {
	return &consumerGroups{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the consumerGroup, and returns the corresponding consumerGroup object, and an error if there is any.
func (c *consumerGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ConsumerGroup, err error) {
	result = &v1alpha1.ConsumerGroup{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("consumergroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ConsumerGroups that match those selectors.
func (c *consumerGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ConsumerGroupList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ConsumerGroupList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("consumergroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested consumerGroups.
func (c *consumerGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("consumergroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a consumerGroup and creates it.  Returns the server's representation of the consumerGroup, and an error, if there is any.
func (c *consumerGroups) Create(ctx context.Context, consumerGroup *v1alpha1.ConsumerGroup, opts v1.CreateOptions) (result *v1alpha1.ConsumerGroup, err error) {
	result = &v1alpha1.ConsumerGroup{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("consumergroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(consumerGroup).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a consumerGroup and updates it. Returns the server's representation of the consumerGroup, and an error, if there is any.
func (c *consumerGroups) Update(ctx context.Context, consumerGroup *v1alpha1.ConsumerGroup, opts v1.UpdateOptions) (result *v1alpha1.ConsumerGroup, err error) {
	result = &v1alpha1.ConsumerGroup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("consumergroups").
		Name(consumerGroup.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(consumerGroup).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *consumerGroups) UpdateStatus(ctx context.Context, consumerGroup *v1alpha1.ConsumerGroup, opts v1.UpdateOptions) (result *v1alpha1.ConsumerGroup, err error) {
	result = &v1alpha1.ConsumerGroup{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("consumergroups").
		Name(consumerGroup.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(consumerGroup).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the consumerGroup and deletes it. Returns an error if one occurs.
func (c *consumerGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("consumergroups").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *consumerGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("consumergroups").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched consumerGroup.
func (c *consumerGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ConsumerGroup, err error) {
	result = &v1alpha1.ConsumerGroup{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("consumergroups").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// GetScale takes name of the consumerGroup, and returns the corresponding autoscalingv1.Scale object, and an error if there is any.
func (c *consumerGroups) GetScale(ctx context.Context, consumerGroupName string, options v1.GetOptions) (result *autoscalingv1.Scale, err error) {
	result = &autoscalingv1.Scale{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("consumergroups").
		Name(consumerGroupName).
		SubResource("scale").
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}
