/*
 * Copyright 2021 The Knative Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "knative.dev/eventing-kafka-broker/control-plane/pkg/apis/internals/kafka/eventing/v1alpha1"
	scheme "knative.dev/eventing-kafka-broker/control-plane/pkg/client/internals/kafka/clientset/versioned/scheme"
)

// ConsumersGetter has a method to return a ConsumerInterface.
// A group's client should implement this interface.
type ConsumersGetter interface {
	Consumers(namespace string) ConsumerInterface
}

// ConsumerInterface has methods to work with Consumer resources.
type ConsumerInterface interface {
	Create(ctx context.Context, consumer *v1alpha1.Consumer, opts v1.CreateOptions) (*v1alpha1.Consumer, error)
	Update(ctx context.Context, consumer *v1alpha1.Consumer, opts v1.UpdateOptions) (*v1alpha1.Consumer, error)
	UpdateStatus(ctx context.Context, consumer *v1alpha1.Consumer, opts v1.UpdateOptions) (*v1alpha1.Consumer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Consumer, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ConsumerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Consumer, err error)
	ConsumerExpansion
}

// consumers implements ConsumerInterface
type consumers struct {
	client rest.Interface
	ns     string
}

// newConsumers returns a Consumers
func newConsumers(c *InternalV1alpha1Client, namespace string) *consumers {
	return &consumers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the consumer, and returns the corresponding consumer object, and an error if there is any.
func (c *consumers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Consumer, err error) {
	result = &v1alpha1.Consumer{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("consumers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Consumers that match those selectors.
func (c *consumers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ConsumerList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ConsumerList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("consumers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested consumers.
func (c *consumers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("consumers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a consumer and creates it.  Returns the server's representation of the consumer, and an error, if there is any.
func (c *consumers) Create(ctx context.Context, consumer *v1alpha1.Consumer, opts v1.CreateOptions) (result *v1alpha1.Consumer, err error) {
	result = &v1alpha1.Consumer{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("consumers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(consumer).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a consumer and updates it. Returns the server's representation of the consumer, and an error, if there is any.
func (c *consumers) Update(ctx context.Context, consumer *v1alpha1.Consumer, opts v1.UpdateOptions) (result *v1alpha1.Consumer, err error) {
	result = &v1alpha1.Consumer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("consumers").
		Name(consumer.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(consumer).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *consumers) UpdateStatus(ctx context.Context, consumer *v1alpha1.Consumer, opts v1.UpdateOptions) (result *v1alpha1.Consumer, err error) {
	result = &v1alpha1.Consumer{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("consumers").
		Name(consumer.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(consumer).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the consumer and deletes it. Returns an error if one occurs.
func (c *consumers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("consumers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *consumers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("consumers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched consumer.
func (c *consumers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Consumer, err error) {
	result = &v1alpha1.Consumer{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("consumers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
