/*
 * Copyright 2021 The Knative Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"
	v1 "knative.dev/eventing-kafka-broker/control-plane/pkg/apis/eventing/v1"
	eventingv1 "knative.dev/eventing-kafka-broker/control-plane/pkg/client/clientset/versioned/typed/eventing/v1"
)

// fakeKafkaSinks implements KafkaSinkInterface
type fakeKafkaSinks struct {
	*gentype.FakeClientWithList[*v1.KafkaSink, *v1.KafkaSinkList]
	Fake *FakeEventingV1
}

func newFakeKafkaSinks(fake *FakeEventingV1, namespace string) eventingv1.KafkaSinkInterface {
	return &fakeKafkaSinks{
		gentype.NewFakeClientWithList[*v1.KafkaSink, *v1.KafkaSinkList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("kafkasinks"),
			v1.SchemeGroupVersion.WithKind("KafkaSink"),
			func() *v1.KafkaSink { return &v1.KafkaSink{} },
			func() *v1.KafkaSinkList { return &v1.KafkaSinkList{} },
			func(dst, src *v1.KafkaSinkList) { dst.ListMeta = src.ListMeta },
			func(list *v1.KafkaSinkList) []*v1.KafkaSink { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.KafkaSinkList, items []*v1.KafkaSink) { list.Items = gentype.FromPointerSlice(items) },
		),
		fake,
	}
}
