package dev.knative.eventing.kafka.broker.core;


/**
 * Broker interface represents the Broker object.
 *
 * <p>Each implementation must override: equals(object) and hashCode(), and those implementation
 * must catch Broker updates (e.g. it's not safe to compare only the Broker UID). It's recommended
 * to not relying on equals(object) and hashCode() generated by Protocol Buffer compiler.
 *
 * <p>Testing equals(object) and hashCode() of newly added implementation is done by adding sources
 * to parameterized tests in BrokerTest.
 */
public interface Broker {

  /**
   * Get broker identifier.
   *
   * @return identifier.
   */
  String id();

  /**
   * Get broker topic.
   *
   * @return topic.
   */
  String topic();

  /**
   * Get Broker dead letter sink.
   *
   * @return dead letter sink.
   */
  String deadLetterSink();
}
