/*
 * Copyright 2020 The Knative Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.knative.eventing.kafka.broker.core;

/**
 * Broker interface represents the Broker object.
 *
 * <p>Each implementation must override: equals(object) and hashCode(), and those implementation
 * must catch Broker updates (e.g. it's not safe to compare only the Broker UID). It's recommended
 * to not relying on equals(object) and hashCode() generated by Protocol Buffer compiler.
 *
 * <p>Testing equals(object) and hashCode() of newly added implementation is done by adding sources
 * to parameterized tests in BrokerTest.
 */
public interface Broker {

  /**
   * Get broker identifier.
   *
   * @return identifier.
   */
  String id();

  /**
   * Get broker topic.
   *
   * @return topic.
   */
  String topic();

  /**
   * Get Broker dead letter sink.
   *
   * @return dead letter sink.
   */
  String deadLetterSink();

  /**
   * Get broker namespace.
   *
   * @return namespace.
   */
  String namespace();

  /**
   * Get broker name.
   *
   * @return name.
   */
  String name();

  /**
   * A comma separated list of host/port pairs to use for establishing the initial connection to the
   * Kafka cluster.
   *
   * @return bootstrap servers.
   */
  String bootstrapServers();

  /**
   * Get request path to accept events for this Broker.
   *
   * @return request path associated with this Broker.
   */
  String path();
}
