/*
 * Copyright 2020 The Knative Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.knative.eventing.kafka.broker.core;

/**
 * Trigger interface represents the Trigger object.
 *
 * <p>Each implementation must override: equals(object) and hashCode(), and those implementation
 * must catch Trigger updates (e.g. it's not safe to compare only the Trigger UID). It's recommended
 * to not relying on equals(object) and hashCode() generated by Protocol Buffer compiler.
 *
 * <p>Testing equals(object) and hashCode() of newly added implementation is done by adding sources
 * to parameterized tests in TriggerTest.
 */
public interface Trigger<T> {

  /**
   * Get trigger id.
   *
   * @return trigger identifier.
   */
  String id();

  /**
   * Get the filter.
   *
   * @return filter to use.
   */
  Filter<T> filter();

  /**
   * Get trigger destination URI.
   *
   * @return destination URI.
   */
  String destination();
}
